"""empty message

Revision ID: 4c4fc6c896a2
Revises: 
Create Date: 2024-10-07 13:46:37.182628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4fc6c896a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.String(length=64), nullable=False),
    sa.Column('group_code', sa.String(length=64), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_groups_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_groups_group_code'), ['group_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_groups_group_type'), ['group_type'], unique=False)

    op.create_table('entity_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(length=64), nullable=False),
    sa.Column('member_first_name', sa.String(length=64), nullable=False),
    sa.Column('member_last_name', sa.String(length=64), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_members_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_group_code'), ['group_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_member_first_name'), ['member_first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_member_last_name'), ['member_last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_title'), ['title'], unique=False)

    op.create_table('entity_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=64), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_name', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_name_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_name_entity_name'), ['entity_name'], unique=False)

    op.create_table('meeting_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('member_type', sa.String(length=64), nullable=True),
    sa.Column('member_present', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_attendance_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_attendance_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_attendance_member_id'), ['member_id'], unique=False)

    op.create_table('meeting_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_entity', sa.String(length=64), nullable=False),
    sa.Column('meeting_type', sa.String(length=64), nullable=True),
    sa.Column('meeting_date', sa.String(length=64), nullable=True),
    sa.Column('meeting_time', sa.String(length=64), nullable=True),
    sa.Column('meeting_time_start', sa.String(length=64), nullable=True),
    sa.Column('meeting_agenda', sa.String(length=32), nullable=True),
    sa.Column('agenda_name', sa.String(length=64), nullable=True),
    sa.Column('agenda_update', sa.String(length=32), nullable=True),
    sa.Column('meeting_minutes', sa.String(length=64), nullable=True),
    sa.Column('audio_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_info_meeting_entity'), ['meeting_entity'], unique=False)

    op.create_table('meeting_motion_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('motion_title', sa.String(length=64), nullable=False),
    sa.Column('agenda_item', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_motion_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_motion_items_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_motion_items_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_motion_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=False),
    sa.Column('motion_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_motion_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_motion_votes_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_motion_votes_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_motion_votes_member_id'), ['member_id'], unique=False)

    op.create_table('prompt_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_file', sa.String(length=64), nullable=False),
    sa.Column('meeting_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_info_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_info_prompt_file'), ['prompt_file'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('user_city', sa.String(length=64), nullable=True),
    sa.Column('user_city_code', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('user_role', sa.String(length=120), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('prompt_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_info_prompt_file'))
        batch_op.drop_index(batch_op.f('ix_prompt_info_meeting_id'))

    op.drop_table('prompt_info')
    with op.batch_alter_table('meeting_motion_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_motion_votes_member_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_motion_votes_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_motion_votes_entity_code'))

    op.drop_table('meeting_motion_votes')
    with op.batch_alter_table('meeting_motion_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_motion_items_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_motion_items_entity_code'))

    op.drop_table('meeting_motion_items')
    with op.batch_alter_table('meeting_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_info_meeting_entity'))

    op.drop_table('meeting_info')
    with op.batch_alter_table('meeting_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_attendance_member_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_attendance_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_attendance_entity_code'))

    op.drop_table('meeting_attendance')
    with op.batch_alter_table('entity_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_name_entity_name'))
        batch_op.drop_index(batch_op.f('ix_entity_name_entity_code'))

    op.drop_table('entity_name')
    with op.batch_alter_table('entity_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_members_title'))
        batch_op.drop_index(batch_op.f('ix_entity_members_position'))
        batch_op.drop_index(batch_op.f('ix_entity_members_member_last_name'))
        batch_op.drop_index(batch_op.f('ix_entity_members_member_first_name'))
        batch_op.drop_index(batch_op.f('ix_entity_members_group_code'))
        batch_op.drop_index(batch_op.f('ix_entity_members_entity_code'))

    op.drop_table('entity_members')
    with op.batch_alter_table('entity_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_groups_group_type'))
        batch_op.drop_index(batch_op.f('ix_entity_groups_group_code'))
        batch_op.drop_index(batch_op.f('ix_entity_groups_entity_code'))

    op.drop_table('entity_groups')
    # ### end Alembic commands ###
