"""empty message

Revision ID: 5163869cd525
Revises: b6b854ecb1f9
Create Date: 2024-08-16 17:34:51.952117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5163869cd525'
down_revision = 'b6b854ecb1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('member_last_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('position', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_entity_members_member_name')
        batch_op.create_index(batch_op.f('ix_entity_members_member_first_name'), ['member_first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_member_last_name'), ['member_last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_title'), ['title'], unique=False)
        batch_op.drop_column('member_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_name', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_entity_members_title'))
        batch_op.drop_index(batch_op.f('ix_entity_members_position'))
        batch_op.drop_index(batch_op.f('ix_entity_members_member_last_name'))
        batch_op.drop_index(batch_op.f('ix_entity_members_member_first_name'))
        batch_op.create_index('ix_entity_members_member_name', ['member_name'], unique=False)
        batch_op.drop_column('position')
        batch_op.drop_column('title')
        batch_op.drop_column('member_last_name')
        batch_op.drop_column('member_first_name')

    # ### end Alembic commands ###
