"""empty message

Revision ID: 5b3544b5f5b1
Revises: 70e88a900841
Create Date: 2024-09-29 12:33:14.027185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3544b5f5b1'
down_revision = '70e88a900841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_name', sa.String(length=64), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_info_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_info_prompt_name'), ['prompt_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_info_prompt_name'))
        batch_op.drop_index(batch_op.f('ix_prompt_info_entity_code'))

    op.drop_table('prompt_info')
    # ### end Alembic commands ###
