"""empty message

Revision ID: 72f252a14a31
Revises: fa17e527cea8
Create Date: 2024-09-29 12:57:38.137565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f252a14a31'
down_revision = 'fa17e527cea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_info', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_info_entity_code')
        batch_op.drop_column('entity_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_code', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_index('ix_prompt_info_entity_code', ['entity_code'], unique=False)

    # ### end Alembic commands ###
