"""empty message

Revision ID: b6b854ecb1f9
Revises: d33e88b55f05
Create Date: 2024-08-16 16:58:32.008624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b854ecb1f9'
down_revision = 'd33e88b55f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.String(length=64), nullable=False),
    sa.Column('group_code', sa.String(length=64), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_groups_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_groups_group_code'), ['group_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_groups_group_type'), ['group_type'], unique=False)

    op.create_table('entity_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(length=64), nullable=False),
    sa.Column('member_name', sa.String(length=64), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_members_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_group_code'), ['group_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_members_member_name'), ['member_name'], unique=False)

    op.create_table('entity_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=64), nullable=False),
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_name', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_name_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_name_entity_name'), ['entity_name'], unique=False)

    with op.batch_alter_table('meeting_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_agenda', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_meeting_info_email')
        batch_op.create_index(batch_op.f('ix_meeting_info_meeting_agenda'), ['meeting_agenda'], unique=False)
        batch_op.drop_column('email')
        batch_op.drop_column('about_me')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_meeting_info_meeting_agenda'))
        batch_op.create_index('ix_meeting_info_email', ['email'], unique=1)
        batch_op.drop_column('meeting_agenda')

    with op.batch_alter_table('entity_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_name_entity_name'))
        batch_op.drop_index(batch_op.f('ix_entity_name_entity_code'))

    op.drop_table('entity_name')
    with op.batch_alter_table('entity_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_members_member_name'))
        batch_op.drop_index(batch_op.f('ix_entity_members_group_code'))
        batch_op.drop_index(batch_op.f('ix_entity_members_entity_code'))

    op.drop_table('entity_members')
    with op.batch_alter_table('entity_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_groups_group_type'))
        batch_op.drop_index(batch_op.f('ix_entity_groups_group_code'))
        batch_op.drop_index(batch_op.f('ix_entity_groups_entity_code'))

    op.drop_table('entity_groups')
    # ### end Alembic commands ###
