"""empty message

Revision ID: d33e88b55f05
Revises: 7ac2f843c851
Create Date: 2024-08-15 16:38:56.293381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33e88b55f05'
down_revision = '7ac2f843c851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.String(length=64), nullable=False),
    sa.Column('meeting_date', sa.DATETIME(), nullable=False),
    sa.Column('meeting_time', sa.DATETIME(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_info_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_meeting_info_meeting_date'), ['meeting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_info_meeting_time'), ['meeting_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_info_meeting_type'), ['meeting_type'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_city', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_city')

    with op.batch_alter_table('meeting_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_info_meeting_type'))
        batch_op.drop_index(batch_op.f('ix_meeting_info_meeting_time'))
        batch_op.drop_index(batch_op.f('ix_meeting_info_meeting_date'))
        batch_op.drop_index(batch_op.f('ix_meeting_info_email'))

    op.drop_table('meeting_info')
    # ### end Alembic commands ###
